### ISSUE TITLE
KeyError: 'ckan_hosts' durante `dpckan dataset update` em conjuntos que não possuem a propriedade `ckan_hosts` com info de host

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/dpckan#132]
Erro encontrado por @Andrelamor durante processo de atualização do [conjunto termos de parceiria](https://github.com/dados-mg/termos-parceria-contratos-gestao).

Inicialmente o arquivo datapackage.json não contava com a propriedade ckan_hosts (incluída recentemente após criação de dataset no ckan utilizando dpckan). O conjunto não tinha pois a criação deste dataset no chan ocorreu antes do dpckan. Mesmo depois de incluir a propriedade o erro ocorreu.

- Devemos tratar os casos em que datapackage não tenha ckan_hosts no momento de atualizações.

```
m6695506@D03GC5234264738 MINGW64 ~/Documents/CGE_transparência/repositorios/dados-mg/termos-parceria-contratos-gestao (master)
$ dpckan dataset update
Atualizando conjunto de dados: termos-parceria-contratos-gestao
Traceback (most recent call last):
File "C:\Users\m6695506\Miniconda3\lib\runpy.py", line 197, in runmodule_as_main
return runcode(code, main_globals, None,
File "C:\Users\m6695506\Miniconda3\lib\runpy.py", line 87, in runcode
exec(code, run_globals)
File "C:\Users\m6695506\Documents\CGE_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\Scripts\dpckan.exe__main.py", line 7, in <module>
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\click\core.py", line 1128, in call
return self.main(args, kwargs)
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\click\core.py", line 1053, in main
rv = self.invoke(ctx)
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\click\core.py", line 1659, in invoke
return processresult(sub_ctx.command.invoke(sub_ctx))
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\click\core.py", line 1659, in invoke
return processresult(sub_ctx.command.invoke(sub_ctx))
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\click\core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\click\core.py", line 754, in invoke
return callback(args, kwargs)
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\dpckan\update_dataset.py", line 77, in update_cli
update(ckan_host, ckan_key, datapackage)
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\dpckan\update_dataset.py", line 37, in update
dataset_update(ckan_instance, package)
File "c:\users\m6695506\documents\cge_transpar▒ncia\repositorios\dados-mg\termos-parceria-contratos-gestao\venv\lib\site-packages\dpckan\functions.py", line 146, in dataset_update
datapackage_id = datapackage['ckan_hosts'][ckan_instance.address]['datapackage.json']
```

**Comment by fjuniorr** [comment]
Também recebi esse erro. 

Vai ser importante explicar o que está acontecendo pra permitir que o usuário consiga se "recuperar" do problema. Pensei em uma mensagem do tipo:

> A propriedade `ckan_hosts` contendo o mapa de associação entre recursos locais e remotos não está disponível.
> 
> Esse conjunto de dados foi publicado com o `dpckan`? Veja como proceder no link https://example.com/docs

No `https://example.com/docs` a gente explica com mais contexto o que está acontecendo e que vai ser necessário alterar o arquivo `datapackage.json` que está armazenado no CKAN.

---

> Mesmo depois de incluir a propriedade o erro ocorreu.

Não entendi isso aqui @gabrielbdornas e @Andrelamor. Vcs incluiram a `ckan_hosts` no `datapackage.json` do CKAN com a associação entre os recursos e o erro continuou?
